// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: face_input.proto

package com.example.face_input.models;

public final class FaceInput {
  private FaceInput() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FaceStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FaceState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float leftEyeOpenProbability = 1;</code>
     * @return The leftEyeOpenProbability.
     */
    float getLeftEyeOpenProbability();

    /**
     * <code>float rightEyeOpenProbability = 2;</code>
     * @return The rightEyeOpenProbability.
     */
    float getRightEyeOpenProbability();

    /**
     * <code>float headEulerAngleY = 3;</code>
     * @return The headEulerAngleY.
     */
    float getHeadEulerAngleY();
  }
  /**
   * Protobuf type {@code FaceState}
   */
  public static final class FaceState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FaceState)
      FaceStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FaceState.newBuilder() to construct.
    private FaceState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FaceState() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FaceState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.face_input.models.FaceInput.internal_static_FaceState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.face_input.models.FaceInput.internal_static_FaceState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.face_input.models.FaceInput.FaceState.class, com.example.face_input.models.FaceInput.FaceState.Builder.class);
    }

    public static final int LEFTEYEOPENPROBABILITY_FIELD_NUMBER = 1;
    private float leftEyeOpenProbability_;
    /**
     * <code>float leftEyeOpenProbability = 1;</code>
     * @return The leftEyeOpenProbability.
     */
    @java.lang.Override
    public float getLeftEyeOpenProbability() {
      return leftEyeOpenProbability_;
    }

    public static final int RIGHTEYEOPENPROBABILITY_FIELD_NUMBER = 2;
    private float rightEyeOpenProbability_;
    /**
     * <code>float rightEyeOpenProbability = 2;</code>
     * @return The rightEyeOpenProbability.
     */
    @java.lang.Override
    public float getRightEyeOpenProbability() {
      return rightEyeOpenProbability_;
    }

    public static final int HEADEULERANGLEY_FIELD_NUMBER = 3;
    private float headEulerAngleY_;
    /**
     * <code>float headEulerAngleY = 3;</code>
     * @return The headEulerAngleY.
     */
    @java.lang.Override
    public float getHeadEulerAngleY() {
      return headEulerAngleY_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(leftEyeOpenProbability_) != 0) {
        output.writeFloat(1, leftEyeOpenProbability_);
      }
      if (java.lang.Float.floatToRawIntBits(rightEyeOpenProbability_) != 0) {
        output.writeFloat(2, rightEyeOpenProbability_);
      }
      if (java.lang.Float.floatToRawIntBits(headEulerAngleY_) != 0) {
        output.writeFloat(3, headEulerAngleY_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(leftEyeOpenProbability_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, leftEyeOpenProbability_);
      }
      if (java.lang.Float.floatToRawIntBits(rightEyeOpenProbability_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, rightEyeOpenProbability_);
      }
      if (java.lang.Float.floatToRawIntBits(headEulerAngleY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, headEulerAngleY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.face_input.models.FaceInput.FaceState)) {
        return super.equals(obj);
      }
      com.example.face_input.models.FaceInput.FaceState other = (com.example.face_input.models.FaceInput.FaceState) obj;

      if (java.lang.Float.floatToIntBits(getLeftEyeOpenProbability())
          != java.lang.Float.floatToIntBits(
              other.getLeftEyeOpenProbability())) return false;
      if (java.lang.Float.floatToIntBits(getRightEyeOpenProbability())
          != java.lang.Float.floatToIntBits(
              other.getRightEyeOpenProbability())) return false;
      if (java.lang.Float.floatToIntBits(getHeadEulerAngleY())
          != java.lang.Float.floatToIntBits(
              other.getHeadEulerAngleY())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LEFTEYEOPENPROBABILITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLeftEyeOpenProbability());
      hash = (37 * hash) + RIGHTEYEOPENPROBABILITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getRightEyeOpenProbability());
      hash = (37 * hash) + HEADEULERANGLEY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeadEulerAngleY());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.face_input.models.FaceInput.FaceState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.face_input.models.FaceInput.FaceState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.face_input.models.FaceInput.FaceState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FaceState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FaceState)
        com.example.face_input.models.FaceInput.FaceStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.face_input.models.FaceInput.internal_static_FaceState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.face_input.models.FaceInput.internal_static_FaceState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.face_input.models.FaceInput.FaceState.class, com.example.face_input.models.FaceInput.FaceState.Builder.class);
      }

      // Construct using com.example.face_input.models.FaceInput.FaceState.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        leftEyeOpenProbability_ = 0F;

        rightEyeOpenProbability_ = 0F;

        headEulerAngleY_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.face_input.models.FaceInput.internal_static_FaceState_descriptor;
      }

      @java.lang.Override
      public com.example.face_input.models.FaceInput.FaceState getDefaultInstanceForType() {
        return com.example.face_input.models.FaceInput.FaceState.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.face_input.models.FaceInput.FaceState build() {
        com.example.face_input.models.FaceInput.FaceState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.face_input.models.FaceInput.FaceState buildPartial() {
        com.example.face_input.models.FaceInput.FaceState result = new com.example.face_input.models.FaceInput.FaceState(this);
        result.leftEyeOpenProbability_ = leftEyeOpenProbability_;
        result.rightEyeOpenProbability_ = rightEyeOpenProbability_;
        result.headEulerAngleY_ = headEulerAngleY_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.face_input.models.FaceInput.FaceState) {
          return mergeFrom((com.example.face_input.models.FaceInput.FaceState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.face_input.models.FaceInput.FaceState other) {
        if (other == com.example.face_input.models.FaceInput.FaceState.getDefaultInstance()) return this;
        if (other.getLeftEyeOpenProbability() != 0F) {
          setLeftEyeOpenProbability(other.getLeftEyeOpenProbability());
        }
        if (other.getRightEyeOpenProbability() != 0F) {
          setRightEyeOpenProbability(other.getRightEyeOpenProbability());
        }
        if (other.getHeadEulerAngleY() != 0F) {
          setHeadEulerAngleY(other.getHeadEulerAngleY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                leftEyeOpenProbability_ = input.readFloat();

                break;
              } // case 13
              case 21: {
                rightEyeOpenProbability_ = input.readFloat();

                break;
              } // case 21
              case 29: {
                headEulerAngleY_ = input.readFloat();

                break;
              } // case 29
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private float leftEyeOpenProbability_ ;
      /**
       * <code>float leftEyeOpenProbability = 1;</code>
       * @return The leftEyeOpenProbability.
       */
      @java.lang.Override
      public float getLeftEyeOpenProbability() {
        return leftEyeOpenProbability_;
      }
      /**
       * <code>float leftEyeOpenProbability = 1;</code>
       * @param value The leftEyeOpenProbability to set.
       * @return This builder for chaining.
       */
      public Builder setLeftEyeOpenProbability(float value) {
        
        leftEyeOpenProbability_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float leftEyeOpenProbability = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeftEyeOpenProbability() {
        
        leftEyeOpenProbability_ = 0F;
        onChanged();
        return this;
      }

      private float rightEyeOpenProbability_ ;
      /**
       * <code>float rightEyeOpenProbability = 2;</code>
       * @return The rightEyeOpenProbability.
       */
      @java.lang.Override
      public float getRightEyeOpenProbability() {
        return rightEyeOpenProbability_;
      }
      /**
       * <code>float rightEyeOpenProbability = 2;</code>
       * @param value The rightEyeOpenProbability to set.
       * @return This builder for chaining.
       */
      public Builder setRightEyeOpenProbability(float value) {
        
        rightEyeOpenProbability_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float rightEyeOpenProbability = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRightEyeOpenProbability() {
        
        rightEyeOpenProbability_ = 0F;
        onChanged();
        return this;
      }

      private float headEulerAngleY_ ;
      /**
       * <code>float headEulerAngleY = 3;</code>
       * @return The headEulerAngleY.
       */
      @java.lang.Override
      public float getHeadEulerAngleY() {
        return headEulerAngleY_;
      }
      /**
       * <code>float headEulerAngleY = 3;</code>
       * @param value The headEulerAngleY to set.
       * @return This builder for chaining.
       */
      public Builder setHeadEulerAngleY(float value) {
        
        headEulerAngleY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float headEulerAngleY = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadEulerAngleY() {
        
        headEulerAngleY_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FaceState)
    }

    // @@protoc_insertion_point(class_scope:FaceState)
    private static final com.example.face_input.models.FaceInput.FaceState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.face_input.models.FaceInput.FaceState();
    }

    public static com.example.face_input.models.FaceInput.FaceState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FaceState>
        PARSER = new com.google.protobuf.AbstractParser<FaceState>() {
      @java.lang.Override
      public FaceState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FaceState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FaceState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.face_input.models.FaceInput.FaceState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FaceState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FaceState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020face_input.proto\"e\n\tFaceState\022\036\n\026leftE" +
      "yeOpenProbability\030\001 \001(\002\022\037\n\027rightEyeOpenP" +
      "robability\030\002 \001(\002\022\027\n\017headEulerAngleY\030\003 \001(" +
      "\002B\037\n\035com.example.face_input.modelsb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FaceState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FaceState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FaceState_descriptor,
        new java.lang.String[] { "LeftEyeOpenProbability", "RightEyeOpenProbability", "HeadEulerAngleY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
